services:
  ml_ops_rest_server:
    build: ./backend
    container_name: ml_ops_rest_server
    restart: unless-stopped
    networks:
      - srv_private

  ml_ops_front_react:
    build: ./frontend
    container_name: ml_ops_front_react
    restart: unless-stopped
    networks:
      - srv_private
    depends_on:
      - ml_ops_rest_server

  ml_ops_web_server:
    build: ./nginx
    container_name: ml_ops_web_server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web_public
      - srv_private
    depends_on:
      - ml_ops_front_react
      - ml_ops_rest_server

networks:
  srv_private:
    internal: true
  web_public:
    name: public
