#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Launch Flask Backend Container
  docker_container:
    name: ml_ops_rest_server
    image: clestrat/ml_ops_rest_server:latest
    networks:
      - name: srv_private
    state: started
    restart_policy: always
