name: Push to Master

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Étape 2 : Connexion à DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 3 : Construire les images Docker
    - name: Build Images
      run: |
        docker-compose -f app/docker-compose.yml build

    # Étape 4 : Taguer les images pour Docker Hub
    - name: Tag Images
      run: |
        docker tag ml_ops_rest_server ${{ secrets.DOCKER_USERNAME }}/ml_ops_rest_server:latest
        docker tag ml_ops_front_react ${{ secrets.DOCKER_USERNAME }}/ml_ops_front_react:latest
        docker tag ml_ops_web_server ${{ secrets.DOCKER_USERNAME }}/ml_ops_web_server:latest

    # Étape 5 : Pousser les images vers DockerHub
    - name: Push Images to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ml_ops_rest_server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ml_ops_front_react:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ml_ops_web_server:latest

    # Étape 6 : Nettoyer les conteneurs après le build
    - name: Clean Up
      run: |
        docker-compose -f app/docker-compose.yml down
