name: Push to Main

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Étape 2 : Connexion à DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 3 : Construire et pousser l'image du backend (rest_server)
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./app/backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rest_server:latest

    # Étape 4 : Construire et pousser l'image du frontend (front_react)
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./app/frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/front_react:latest

    # Étape 5 : Construire et pousser l'image du serveur web (web_server)
    - name: Build and Push Web Server Image
      uses: docker/build-push-action@v5
      with:
        context: ./app/web_server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/web_server:latest
